### PR TITLE
Add basic homeflag impl and update action ids

### PR DESCRIPTION
**Pull request by WolfwithSword**
- Added basic homeflag implementation for parsing basic values
- Updated action id's with new recent additions
- Added a few filaments missing from HA-Bambulab port
- Updated push_all data setting due to new X1 firmware
- Fixed setup.py requirements 
- Added packaging package to enable firmware versioning checks for future use (see door-sensor)

Will merge into a develop branch once it is created. Main branch should ideally be whatever is recent pushed version to pip with appropriate version number changes. Currently is set to main - will edit once made.

### CODE REVIEW

**Comment by AdrianGarside** [comment]
I added this in a modified form to ha-bambulab. Since all the sensors were boolean sensors I made the home_flags properties boolean properties. For the moment I disabled the version check for the X1 door since the version isn't available at the time HA needs to know whether the door sensor exists or not. I'm thinking I'll just make the sensor unavailable on an X1 with too early a version since the availability check is done dynamically.

**Comment by WolfwithSword** [comment]
Yeah the door will be "closed" if it's detected using an older FW or non X1 series.

Thought behind doing it dynamically was such that with the FW version unknown we can simply return it as closed (or others as false) until it's retrieved, since sensors change all the time anyways.

Feel free to close or modify this PR to implement the solution you put into the ha-bambulab - might be a good idea to add in the other stuff such as the new P1 upgrade kit stuff, which luckily has a is_supported flag so no need to version check.

**Comment by AdrianGarside** [comment]
Can do.

The problem with the version as used here is that you have to do the 'exists' check before we have the version to answer it when running in home assistant (or post-upgrade if we'd cached the version it would be wrong). So I split it apart in my version of this change - exists is now based on just a standard model check (model is persisted into the integration config so we always know that immediately precisely for exists checks like this) and a separate available check that additionally takes version into account. So an X1 with < 1.7 will have the sensor present but it will be permanently unavailable where P1/A1 won't have the sensor at all.

I already added the P1 upgrade kit although I haven't yet decided if/how it can be used by the integration.

**Comment by AdrianGarside** [comment]
@WolfwithSword I've copied over a snapshot from ha-bambulab. Take a look and let me know what you think. It should be at parity with what you had here.

**Comment by WolfwithSword** [comment]
> @WolfwithSword I've copied over a snapshot from ha-bambulab. Take a look and let me know what you think. It should be at parity with what you had here.

Looks good to me, will close PR then!

**Pull request closed without merging**
